name: Publish Shopware Docker image to Docker Hub
on: [push]

jobs:
    build:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache node modules
              uses: actions/cache@v1
              env:
                  cache-name: cache-composer-modules
              with:
                  path: vendor
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Composer install
              uses: docker://composer:1.9.1
              with:
                  args: install --ignore-platform-reqs
            - name: Publish to registry
              uses: HurricanKai/Publish-Docker-Github-Action@master
              with:
                  name: fbdo/shopware
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
